### ISSUE TITLE
Why min_val is zero on minmax_norm function

### ISSUE THREAD

**Issue by jd730** [Pilhyeon/BaSNet-pytorch#1]
Hi.
Why `minmax_norm` actually works scores / (max_scores per each class) (here is [code](https://github.com/Pilhyeon/BaSNet-pytorch/blob/e3cffb4245ccc44d6c9456817f8b54333161ef62/utils.py#L77))? 

I found that there is a case that max_score is negative which means that sign is flipped due to minmax_norm.

Thank you!

**Comment by Pilhyeon** [comment]
It was originally intended to ignore negative activation values, but it must be a bug for the case.
We have fixed it. Please refer to the commit f52240e0.
Thank you.

**Comment by jd730** [comment]
I think it occurs divide by zero error when the max_score is negative. Thank you for reply.

**Comment by jd730** [comment]
I made a pull request to fix this problem, but actually it does not affect since problematic class actually is not used since its class score is lower than a threshold.

cf. In the first video in test dataset, max_val of 4th class is -4.4045e-02.

**Comment by Pilhyeon** [comment]
Actually, 'divide by zero' error means that all activation values are 0, which hardly occurs.
However, considering your concern, we accepted your pull request.

Thank you.

**Comment by jd730** [comment]
Thank you.
