### ISSUE TITLE
Could you share the visualization code of showing  the Base and Suppression score curve?

### ISSUE THREAD

**Issue by JacobKong** [Pilhyeon/BaSNet-pytorch#3]
Dear friend:

Could you share the visualization code of showing  the Base and Suppression score curve as your paper?

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/10401849/70385793-79c17b00-19cb-11ea-9516-50e6a98958d1.png">

Thanks a lot.

**Comment by Pilhyeon** [comment]
Thanks for your interest.
Nonetheless, we have no plan to release the visualization code now.
We're sorry for that.
