### ISSUE TITLE
Why is there a sudden change after 150 steps in mAP test result during training?

### ISSUE THREAD

**Issue by demianzhang** [Pilhyeon/BaSNet-pytorch#9]
I find the test mAP before 150 is all zero.

**Comment by jiangerxiaozhao** [comment]
Can you reproduce the ActivityNet1.3 or ActivityNet1.2?

**Comment by jiangerxiaozhao** [comment]
> I find the test mAP before 150 is all zero.
Can you reproduce the ActivityNet1.3 or ActivityNet1.2?

**Comment by demianzhang** [comment]
> Can you reproduce the ActivityNet1.3 or ActivityNet1.2?

I haven't tried to reproduce it on other dataset except Thumos14 the author provided.

**Comment by jiangerxiaozhao** [comment]
> > Can you reproduce the ActivityNet1.3 or ActivityNet1.2?
> 
> I haven't tried to reproduce it on other dataset except Thumos14 the author provided.
> BTW, can you explain the reason of this issue when you train it on Thumos14?

On the surface,  "foreground weights" can't learn useful information at the beginning, it can be found from the log of loss_norm. And BaSNet uses the output of the suppression branch for inference.

**Comment by demianzhang** [comment]
> > > Can you reproduce the ActivityNet1.3 or ActivityNet1.2?
> > 
> > 
> > I haven't tried to reproduce it on other dataset except Thumos14 the author provided.
> > BTW, can you explain the reason of this issue when you train it on Thumos14?
> 
> On the surface, "foreground weights" can't learn useful information at the beginning, it can be found from the log of loss_norm. And BaSNet uses the output of the suppression branch for inference.

Thanks for your reply.
